package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="User")
public class User {
     
    private String userId;
    private String userName;
    private String bornDate;
    private String updateTime;

    @DynamoDBHashKey(attributeName="user_id")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return userId;
    }
    public User setUserId(String userId) {
        this.userId = userId;
        return this;
    }
     
    @DynamoDBAttribute(attributeName="user_name")
    public String getUserName() {
        return userName;
    }
    public User setUserName(String userName) {
        this.userName = userName;
        return this;
    }
     
    @DynamoDBAttribute(attributeName="born_date")
    public String getBornDate() {
        return bornDate;
    }
    public User setBornDate(String bornDate) {
        this.bornDate = bornDate;
        return this;
    }
     
    @DynamoDBRangeKey(attributeName="update_time")
    public String getUpdateTime() {
        return updateTime;
    }
    public User setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
        return this;
    }
}